<?php

namespace Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class RestaurantTest extends TestCase
{
    protected $header = [];


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->header['Accept'] = 'application/json';
    }

    /**
     * A basic test example helps to sort based on sort values
     *
     * @return void
     */
    public function testSortValue()
    {
        $response = $this->withHeaders([
            'Content-Type' =>  $this->header['Accept']
        ])->json('POST', 'sorting', ['sorting' => 'newest']);

        $response->assertStatus(200)->assertJsonFragment([
            'errors' => null,
            'status' => 'success',
            'message' => 'success'
        ]);
    }

    /**
     * A basic test example helps to sort based on sort values
     *
     * @return void
     */
    public function testWithInvalidSortValue()
    {
        $response = $this->withHeaders([
            'Content-Type' =>  $this->header['Accept']
        ])->json('POST', 'sorting', ['sorting' => 'random']);

        $response->assertStatus(400)->assertJsonFragment([
            'errors' => 'failed'
        ]);
    }
}
